#!/usr/bin/env bash
# Vendor the Moveo One tag and the schema fixture suite from the sibling
# Chrome-extension repo (the normative source — docs/README.md). Adapted from
# the iOS repo's Scripts/vendor-tag.sh (docs/plan.md §0: paths + TagEndpoint.kt).
#
#   - app/src/main/assets/moveo-one.js   byte-identical copy of the tag (NEVER
#                                        edit; parity with desktop data is the
#                                        product promise)
#   - app/src/main/assets/VENDOR.json    provenance: source commit, sha256, date
#   - docs/examples/sainsburys-sg-rules.json  example config for the M6 real-site check
#   - studycore/src/test/resources/fixtures/*.json
#                                        the validator acceptance suite (M1)
#   - studycore/src/main/kotlin/one/moveo/studycore/generated/TagEndpoint.kt
#                                        the ingestion URL baked into the tag —
#                                        the app refuses configs whose apiUrl
#                                        differs, because the tag would ignore
#                                        them silently
#
# Re-run whenever the extension repo updates the tag or fixtures; commit the
# result. The recorded commit hash is how tag updates ship deliberately
# (phase-a4 §a4.4).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
EXT="${MOVEO_EXT_REPO:-$ROOT/../../chrome-extension/moveo_one_chrome_extension}"

if [[ ! -f "$EXT/extension/moveo-one.js" ]]; then
  echo "error: extension repo not found at $EXT (set MOVEO_EXT_REPO to override)" >&2
  exit 1
fi

ASSETS="$ROOT/app/src/main/assets"
GENDIR="$ROOT/studycore/src/main/kotlin/one/moveo/studycore/generated"
mkdir -p "$ASSETS" "$GENDIR" "$ROOT/docs/examples"

# ── Tag (byte-identical) ─────────────────────────────────────────────────────
cp "$EXT/extension/moveo-one.js" "$ASSETS/moveo-one.js"
cmp "$EXT/extension/moveo-one.js" "$ASSETS/moveo-one.js" \
  || { echo "error: vendored tag is not byte-identical" >&2; exit 1; }

# ── Fixture suite ────────────────────────────────────────────────────────────
FIXDIR="$ROOT/studycore/src/test/resources/fixtures"
rm -rf "$FIXDIR"
mkdir -p "$FIXDIR"
cp "$EXT"/docs/schema/fixtures/*.json "$FIXDIR/"

# ── Real-site example config (M6) ────────────────────────────────────────────
cp "$EXT/docs/examples/sainsburys-sg-rules.json" "$ROOT/docs/examples/sainsburys-sg-rules.json"

# ── Extract the tag's baked-in ingestion URL → generated Kotlin constant ─────
TAG_API_URL="$(sed -n 's/.*const API_URL = "\([^"]*\)".*/\1/p' "$ASSETS/moveo-one.js" | head -1)"
if [[ -z "$TAG_API_URL" ]]; then
  echo "error: could not extract API_URL from moveo-one.js — tag format changed?" >&2
  exit 1
fi
cat > "$GENDIR/TagEndpoint.kt" <<EOF
// GENERATED by scripts/vendor-tag.sh — do not edit.
// The ingestion URL baked into app/src/main/assets/moveo-one.js. The tag has
// no runtime endpoint override, so the validator refuses configs whose
// tracking.apiUrl differs (events would silently go here regardless). Mirrors
// the extension's src/tag-endpoint.js guard.
package one.moveo.studycore.generated

object TagEndpoint {
    const val apiUrl: String = "$TAG_API_URL"
}
EOF

# ── Provenance record ────────────────────────────────────────────────────────
COMMIT="$(git -C "$EXT" rev-parse HEAD)"
DIRTY=false
if [[ -n "$(git -C "$EXT" status --porcelain -- extension/moveo-one.js docs/schema/fixtures docs/examples 2>/dev/null)" ]]; then
  DIRTY=true
fi
SHA="$(shasum -a 256 "$ASSETS/moveo-one.js" | awk '{print $1}')"
FIXCOUNT="$(ls "$FIXDIR"/*.json | wc -l | tr -d ' ')"
cat > "$ASSETS/VENDOR.json" <<EOF
{
  "source": "chrome-extension/moveo_one_chrome_extension",
  "sourceCommit": "$COMMIT",
  "sourceDirty": $DIRTY,
  "vendoredAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "files": {
    "moveo-one.js": { "sha256": "$SHA" },
    "fixtures": { "count": $FIXCOUNT }
  }
}
EOF

echo "vendored moveo-one.js  sha256 ${SHA:0:12}…  source ${COMMIT:0:8}$($DIRTY && echo ' (DIRTY WORKING TREE)')"
echo "vendored $FIXCOUNT fixtures → studycore/src/test/resources/fixtures/"
echo "generated TagEndpoint.kt  ($TAG_API_URL)"
